### ISSUE TITLE
Request for Normalized Spectrum Gap Plotting Code

### ISSUE THREAD

**Issue by heyoon01** [rinongal/swagan#1]
Hi! Thanks for sharing your work!
I would love to know details on how you plotted the normalized spectrum gap.
Are you planning to upload it any time soon?

Thanks.

**Comment by rinongal** [comment]
Hi! Absolutely. We put it on a back-burner due to what appeared like limited interest, but since you asked for it I'll make an effort to get it up soon.

How urgently do you need access to the code? There's a big conference deadline coming up so I'll only be able to get around to it towards the end of the month. If you need the code beforehand, I could send you the current messy version of the scripts.

**Comment by heyoon01** [comment]
Could you send me your current version to heyoon@postech.ac.kr ?
Thank you so much for your kind and fast response!
And good luck on your next work!

**Comment by rinongal** [comment]
Thank you!

I'll send it by the end of the day (possibly tomorrow morning for you).

**Comment by rinongal** [comment]
Sent. Let me know if you need further help.

**Comment by hkchae96** [comment]
Hi, could I also get the messy version of  normalized spectrum gap plot code? 
I do have a version of mine, but I'd like to reproduce the spectrum figure more accurately ..! 
chaewon.kim@klleon.io  <- this is my email address :)
Thanks.

**Comment by rinongal** [comment]
Sent

**Comment by kobeshegu** [comment]
> Sent

Hi, Rinon.
Thanks for your great work!
Could you please send to normalized spectrum gap plot code?
My emal is kobeshegu@gmail.com
Thanks.

**Comment by rinongal** [comment]
Sent!

**Comment by flynnamy** [comment]
Hi, Could you please send to normalized spectrum gap plot code? My emal is clearlove1027@gmail.com. Thanks! @rinongal

**Comment by rinongal** [comment]
Sent!
